__title__ = "vk-client"
__version__ = "0.2.0"
__description__ = "Python 2/3 high level VK API."
__url__ = "https://github.com/Suenweek/vk-client"
__author__ = "Roman Novatorov"
__author_email__ = "roman.novatorov@gmail.com"
